[package]
name = "tsukiyomi-fetch"
version = "0.1.0"
edition = "2024"
description = "A performance-optimized Rust-powered stats fetcher with async API calls, 24h intelligent caching, and customizable Fastfetch wrappers for platforms like GitHub, Discord, Codeforces, LeetCode, and more."
license = "MIT"
repository = "https://github.com/Thunder-Blaze/Tsukiyomi-Fetch"
keywords = ["cli", "api", "scraping"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
anyhow = "1.0"
dirs = "5.0"
regex = "1.11.1"
thiserror = "1.0"
once_cell = "1.19"
